NK-3832 Add method to run exec on docker
Stratoscale/docker-test-tools pull request #48
Opened 2022-10-25 14:50 UTC by arielagenin-zadara

2022-10-26 12:52 UTC, shaitourchin requested changes

2022-10-26 12:52 UTC, shaitourchin commented on docker_test_tools/environment.py
> +    def run_exec_in_container(self, name, command):
Please look at the other functions in this file that work on containers and make this one similar to them.
For example:
1. The other functions start with a docstring
2. The other functions start with a log.debug message

2022-10-31 09:34 UTC, shaitourchin requested changes

2022-10-31 09:34 UTC, shaitourchin commented on docker_test_tools/environment.py
> +        :param str name: command to run in the container.
Please fix the argument name

2022-10-31 09:34 UTC, shaitourchin commented on docker_test_tools/environment.py
> +        Execute command on container by name
```suggestion
        Execute command in container by container name
```

2022-10-31 09:34 UTC, shaitourchin commented on docker_test_tools/environment.py
> +            raise RuntimeError("Failed to start exec instance for container %s with command %s" % (name, command))
```suggestion
            raise RuntimeError("Failed to start exec instance in container %s with command %s" % (name, command))
```

2022-10-31 09:34 UTC, shaitourchin commented on docker_test_tools/environment.py
> +        log.debug("Starting exec instance for container %s", name)
```suggestion
        log.debug("Starting exec instance in container %s", name)
```

2022-10-31 11:18 UTC, shaitourchin approved these changes

2022-10-31 11:52 UTC, grishatsukerman approved these changes

2022-11-02 07:46 UTC, merged